export const REQUEST_FETCH_STATES = 'REQUEST_FETCH_STATES'
export const SUCCESS_FETCH_STATES = 'SUCCESS_FETCH_STATES'

export const REQUEST_FETCH_CITIES = 'REQUEST_FETCH_CITIES'
export const SUCCESS_FETCH_CITIES = 'SUCCESS_FETCH_CITIES'

export const REQUEST_FETCH_LOCALITIES = 'REQUEST_FETCH_LOCALITIES'
export const SUCCESS_FETCH_LOCALITIES = 'SUCCESS_FETCH_LOCALITIES'
