export const REQUEST_FETCH_STATES = 'REQUEST_FETCH_STATES'
export const SUCCESS_FETCH_STATES = 'SUCCESS_FETCH_STATES'

export const REQUEST_FETCH_CITIES = 'REQUEST_FETCH_CITIES'
export const SUCCESS_FETCH_CITIES = 'SUCCESS_FETCH_CITIES'

export const REQUEST_CREATE_STATE = 'REQUEST_CREATE_STATE'
export const SUCCESS_CREATE_STATE = 'SUCCESS_CREATE_STATE'

export const REQUEST_CREATE_CITY = 'REQUEST_CREATE_CITY'
export const SUCCESS_CREATE_CITY = 'SUCCESS_CREATE_CITY'

export const REQUEST_UPDATE_STATE = 'REQUEST_UPDATE_STATE'
export const SUCCESS_UPDATE_STATE = 'SUCCESS_UPDATE_STATE'

export const REQUEST_UPDATE_CITY = 'REQUEST_UPDATE_CITY'
export const SUCCESS_UPDATE_CITY = 'SUCCESS_UPDATE_CITY'

export const REQUEST_VIEW_GEOBOUNDARY = 'REQUEST_VIEW_GEOBOUNDARY'
export const SUCCESS_VIEW_GEOBOUNDARY = 'SUCCESS_VIEW_GEOBOUNDARY'

export const REQUEST_UPDATE_GEOBOUNDARY = 'REQUEST_UPDATE_GEOBOUNDARY'
export const SUCCESS_UPDATE_GEOBOUNDARY = 'SUCCESS_UPDATE_GEOBOUNDARY'

export const REQUEST_FETCH_LOCALITIES = 'REQUEST_FETCH_LOCALITIES'
export const SUCCESS_FETCH_LOCALITIES = 'SUCCESS_FETCH_LOCALITIES'

export const REQUEST_CREATE_GEOLOCALITY = 'REQUEST_CREATE_GEOLOCALITY'
export const SUCCESS_CREATE_GEOLOCALITY = 'SUCCESS_CREATE_GEOLOCALITY'

export const REQUEST_UPDATE_GEOLOCALITY = 'REQUEST_UPDATE_GEOLOCALITY'
export const SUCCESS_UPDATE_GEOLOCALITY = 'SUCCESS_UPDATE_GEOLOCALITY'

export const REQUEST_SET_GEOBOUNDARY_LOADING_STATE = 'REQUEST_SET_GEOBOUNDARY_LOADING_STATE'
export const SUCCESS_SET_GEOBOUNDARY_LOADING_STATE = 'SUCCESS_SET_GEOBOUNDARY_LOADING_STATE'

export const REQUEST_SET_GEOLOCALITY_LOADING_STATE = 'REQUEST_SET_GEOLOCALITY_LOADING_STATE'
export const SUCCESS_SET_GEOLOCALITY_LOADING_STATE = 'SUCCESS_SET_GEOLOCALITY_LOADING_STATE'
